name: shared_preferences
description: Flutter plugin for reading and writing simple key-value pairs.
  Wraps NSUserDefaults on iOS and SharedPreferences on Android.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/shared_preferences
version: 0.5.2

flutter:
  plugin:
    androidPackage: io.flutter.plugins.sharedpreferences
    iosPrefix: FLT
    pluginClass: SharedPreferencesPlugin

dependencies:
  meta: ^1.0.4
  flutter_web: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  build_runner: ^1.2.2
  build_web_compilers: ^1.1.0

# environment:
#   sdk: ">=2.0.0-dev.28.0 <3.0.0"
#   flutter: ">=0.1.4 <2.0.0"

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui